service: test-serverless-framework
frameworkVersion: '3'

custom:
  tableName: '${sls:stage}-loyalty-cards-table'
  # Local DynamoDB settings
  serverless-dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ UsersTable, Arn ]
  environment:
    # TO-DO: setup .env
    LOYALTY_CARDS_TABLE_NAME: ${self:custom.tableName}
    DB_HANDLER_PROVIDER: ${env:DB_HANDLER_PROVIDER}
    AWS_REGION: ${env:AWS_REGION}
    DYNAMO_DB_ENDPOINT: ${env:DYNAMO_DB_ENDPOINT}
    DYNAMO_DB_ACCESS_KEY: ${env:DYNAMO_DB_ACCESS_KEY}
    DYNAMO_DB_SECRET_KEY: ${env:DYNAMO_DB_SECRET_KEY}

functions:
  createLoyaltyCard:
    handler: src/httpHandler.createLoyaltyCard
    events:
      - httpApi:
          path: /loyalty-cards
          method: post
    # TO-DO: Add Dead Letter Queue
  findLoyaltyCard:
    handler: src/httpHandler.findLoyaltyCard
    events:
      - httpApi:
          path: /loyalty-cards/{cardNumber}
          method: get
  listLoyaltyCards:
    handler: src/httpHandler.listLoyaltyCards
    events:
      - httpApi:
          path: /loyalty-cards
          method: get

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: cardNumber
            AttributeType: S
        KeySchema:
          - AttributeName: cardNumber
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dynamodb
